### ISSUE TITLE
Hey My Windows' build is failing

### ISSUE THREAD

**Issue by drexhacker** [GetStream/stream-video-flutter#844]
Am using flutter 3.27 stable. and 
```yaml
  stream_chat_flutter: ^9.2.0+1
  stream_video_flutter: ^0.7.2
  stream_video_push_notification: ^0.7.2
  stream_video_screen_sharing: ^0.7.2
```
Here is the error
```
Building Windows application...                                 
CMake Deprecation Warning at D:/a/hse/hse/build/windows/x64/extracted/firebase_cpp_sdk_windows/CMakeLists.txt:17 (cmake_minimum_required):
  Compatibility with CMake < 3.5 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value or use a ...<max> suffix to tell
  CMake that the project does not need compatibility with older versions.


CMake Error:
  Error evaluating generator expression:

    $<TARGET_FILE:stream_webrtc_flutter_plugin>

  No target "stream_webrtc_flutter_plugin"
```
